FROM ruby:2.3

RUN apt-get update \
    && apt-get install nodejs -y \
    && apt-get install -y libqt4-webkit libqt4-dev xvfb \
    && rm -rf /var/lib/apt/lists/*

RUN gem install bundler

ENV APP_HOME /share
ENV RACK_ENV production

RUN mkdir $APP_HOME
WORKDIR $APP_HOME

ADD Gemfile* $APP_HOME/
RUN bundle install

ADD ./ /share

ENV PORT 3000

CMD ["/bin/bash", "-l", "-c", "rails s Puma -b 0.0.0.0 -e production -p 3000"]
