# This is our PRODUCTION dockerfile.
FROM ruby:2.5

RUN apt-get update \
    && apt-get install nodejs -y \
    && apt-get install -y libqtwebkit4 libqt4-dev xvfb \
    && rm -rf /var/lib/apt/lists/*

RUN gem install bundler

EXPOSE 3000

WORKDIR /share
ADD Gemfile /share/Gemfile
ADD Gemfile.lock /share/Gemfile.lock
RUN bundle install --with development


ADD ./ /share
