FROM ruby:2.3

RUN apt-get update \
    && apt-get install nodejs -y \
    && apt-get install -y --no-install-recommends \
        postgresql-client \
    && apt-get install sqlite3 libsqlite3-dev -y \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /share
COPY Gemfile* ./
RUN bundle install
COPY . .

EXPOSE 3000
